[theme]
base                  = "dark"
backgroundColor       = "#11111b"
secondaryBackgroundColor = "#1e1e2e"
primaryColor          = "#89b4fa"
textColor             = "#cdd6f4"
font                  = "sans serif"

[server]
headless = true
